version: '3.8'

services:

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  ecom-app:
    build: .
    container_name: ecom-app
    depends_on:
      - postgres-db
    ports:
      - "8081:8080"
    volumes:
      - ./application.yml:/config/application.yml
    environment:
      SPRING_CONFIG_LOCATION: file:/config/application.yml
    restart: always

volumes:
  pgdata: